jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: latest
    - continue-on-error: true
      name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        key: cljdeps-${{ hashFiles('deps.edn') }}
        path: '~/.m2/repository

          ~/.gitlibs

          '
        restore-keys: cljdeps-
    - continue-on-error: true
      name: Clone clojure api doc repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: clojure-api-doc
        repository: clojure/clojure-api-doc
    - continue-on-error: true
      name: Clone clojure source code repo into clojure-api-doc
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: clojure-api-doc/repo
    - continue-on-error: true
      name: Clone clojure gh-pages branch into clojure-api-doc
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: clojure-api-doc/repo-docs
        ref: gh-pages
        repository: clojure/clojure
    - continue-on-error: true
      name: Install markdown
      run: sudo apt install markdown
    - continue-on-error: true
      name: Call clojure-api-doc build.sh
      run: bash ${GITHUB_WORKSPACE}/clojure-api-doc/build.sh
    - continue-on-error: true
      if: ${{inputs.commit}}
      name: Commit
      run: 'git config --global user.name clojure-build

        git config --global user.email "clojure-build@users.noreply.github.com"

        cd clojure-api-doc/repo-docs

        git add -u -v

        git commit -m "Autodoc commit"

        git push origin gh-pages

        '
name: Build API Docs
on:
  repository_dispatch:
    types: trigger-ga___doc-build.yml
