jobs:
  call-release:
    secrets: inherit
    uses: clojure/build.ci/.github/workflows/release.yml@master
    with:
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      snapshotVersion: ${{ github.event.inputs.snapshotVersion }}
name: Release on demand
on:
  repository_dispatch:
    types: trigger-ga___release.yml
